var myCharacterEnemies = {
    enemies: [],
    generateEnemies: function(scene) {
        for (var e=0; e<scene.enemiesMax - scene.enemies.length; e++) {
            this.enemies.push(myEnemiesProperties[String(e)]);
            this.enemies[e].img = myPreload.images[this.enemies[e].img]
        }
        return this.enemies;
    }
}

var myEnemiesProperties = {
    length: 10,
    0: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy0',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [3, "ropeH"],
            undefined,
            undefined,
            [6, "ropeH"],
            undefined,
            undefined,
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            [0, "ropeV"],
            [1, "ropeV"],
            [2, "ropeV"],
            [3, "ropeH"],
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            [12, "ropeH"],
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            [20, "ropeH"],
            [21, "ropeV"],
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined,
            [15, "ropeV"],
            [16, "ropeV"],
            [17, "ropeH"],
            [18, "ropeH"],
            [19, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    1: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy1',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [3, "ropeH"],
            undefined,
            undefined,
            [6, "ropeH"],
            undefined,
            undefined,
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            [0, "ropeV"],
            [1, "ropeV"],
            [2, "ropeV"],
            [3, "ropeH"],
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            [12, "ropeH"],
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            [20, "ropeH"],
            [21, "ropeV"],
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined,
            [15, "ropeV"],
            [16, "ropeV"],
            [17, "ropeH"],
            [18, "ropeH"],
            [19, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    2: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy2',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [3, "ropeH"],
            undefined,
            undefined,
            [6, "ropeH"],
            undefined,
            undefined,
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            [0, "ropeV"],
            [1, "ropeV"],
            [2, "ropeV"],
            [3, "ropeH"],
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            [12, "ropeH"],
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            [20, "ropeH"],
            [21, "ropeV"],
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined,
            [15, "ropeV"],
            [16, "ropeV"],
            [17, "ropeH"],
            [18, "ropeH"],
            [19, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    3: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy3',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [3, "ropeH"],
            undefined,
            undefined,
            [6, "ropeH"],
            undefined,
            undefined,
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            [0, "ropeV"],
            [1, "ropeV"],
            [2, "ropeV"],
            [3, "ropeH"],
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            [12, "ropeH"],
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            [20, "ropeH"],
            [21, "ropeV"],
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined,
            [15, "ropeV"],
            [16, "ropeV"],
            [17, "ropeH"],
            [18, "ropeH"],
            [19, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    4: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy4',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [3, "ropeH"],
            undefined,
            undefined,
            [6, "ropeH"],
            undefined,
            undefined,
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            [0, "ropeV"],
            [1, "ropeV"],
            [2, "ropeV"],
            [3, "ropeH"],
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            [12, "ropeH"],
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            [20, "ropeH"],
            [21, "ropeV"],
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined,
            [15, "ropeV"],
            [16, "ropeV"],
            [17, "ropeH"],
            [18, "ropeH"],
            [19, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    5: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy5',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [3, "ropeH"],
            undefined,
            undefined,
            [6, "ropeH"],
            undefined,
            undefined,
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            [0, "ropeV"],
            [1, "ropeV"],
            [2, "ropeV"],
            [3, "ropeH"],
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            [12, "ropeH"],
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            [20, "ropeH"],
            [21, "ropeV"],
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined,
            [15, "ropeV"],
            [16, "ropeV"],
            [17, "ropeH"],
            [18, "ropeH"],
            [19, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    6: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy6',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [3, "ropeH"],
            undefined,
            undefined,
            [6, "ropeH"],
            undefined,
            undefined,
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            [0, "ropeV"],
            [1, "ropeV"],
            [2, "ropeV"],
            [3, "ropeH"],
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            [12, "ropeH"],
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            [20, "ropeH"],
            [21, "ropeV"],
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined,
            [15, "ropeV"],
            [16, "ropeV"],
            [17, "ropeH"],
            [18, "ropeH"],
            [19, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    7: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy7',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [3, "ropeH"],
            undefined,
            undefined,
            [6, "ropeH"],
            undefined,
            undefined,
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            [0, "ropeV"],
            [1, "ropeV"],
            [2, "ropeV"],
            [3, "ropeH"],
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            [12, "ropeH"],
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            [20, "ropeH"],
            [21, "ropeV"],
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined,
            [15, "ropeV"],
            [16, "ropeV"],
            [17, "ropeH"],
            [18, "ropeH"],
            [19, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    8: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy8',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [3, "ropeH"],
            undefined,
            undefined,
            [6, "ropeH"],
            undefined,
            undefined,
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            [0, "ropeV"],
            [1, "ropeV"],
            [2, "ropeV"],
            [3, "ropeH"],
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            [12, "ropeH"],
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            [20, "ropeH"],
            [21, "ropeV"],
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined,
            [15, "ropeV"],
            [16, "ropeV"],
            [17, "ropeH"],
            [18, "ropeH"],
            [19, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    9: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy9',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [3, "ropeH"],
            undefined,
            undefined,
            [6, "ropeH"],
            undefined,
            undefined,
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            [0, "ropeV"],
            [1, "ropeV"],
            [2, "ropeV"],
            [3, "ropeH"],
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            [12, "ropeH"],
            [13, "ropeH"],
            [14, "ropeV"],
            [15, "ropeV"],
            undefined,
            undefined,
            undefined,
            undefined,
            [20, "ropeH"],
            [21, "ropeV"],
            [22, "ropeV"],
            [23, "ropeV"]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [4, "ropeH"],
            undefined,
            [6, "ropeH"],
            [7, "ropeV"],
            [8, "ropeV"],
            [9, "ropeV"],
            [10, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined,
            [15, "ropeV"],
            [16, "ropeV"],
            [17, "ropeH"],
            [18, "ropeH"],
            [19, "ropeH"],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    }
}