var myCharacterEnemies = {
    enemies: [],
    generateEnemies: function(scene) {
        for (var e=0; e<scene.enemiesMax - scene.enemies.length; e++) {
            this.enemies.push(myEnemiesProperties[String(e)]);
            this.enemies[e].img = myPreload.images[this.enemies[e].img]
        }
        return this.enemies;
    }
}
//rope[deleted, pos, "image name", type] type = 0:simple, 1:double, 3:directionable negative, 4:directionable positive
var myEnemiesProperties = {
    length: 10,
    0: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy0',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [0,3, "ropeH",0],
            undefined,
            undefined,
            [0,6, "ropeH",0],
            undefined,
            undefined,
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            [0,0, "ropeV",0],
            [0,1, "ropeV",0],
            [0,2, "ropeV",0],
            [0,3, "ropeH",0],
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            [0,12, "ropeH",0],
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,20, "ropeH",0],
            [0,21, "ropeV",0],
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,15, "ropeV",0],
            [0,16, "ropeV",0],
            [0,17, "ropeH",0],
            [0,18, "ropeH",0],
            [0,19, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    1: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy1',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [0,3, "ropeH",1],
            undefined,
            undefined,
            [0,6, "ropeH",1],
            undefined,
            undefined,
            [0,9, "ropeV",1],
            [0,10, "ropeH",1],
            undefined,
            undefined,
            [0,13, "ropeH",1],
            [0,14, "ropeV",1],
            [0,15, "ropeV",1],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [0,22, "ropeV",1],
            [0,23, "ropeV",1]
        ],[
            [0,0, "ropeV",1],
            [0,1, "ropeV",1],
            [0,2, "ropeV",1],
            [0,3, "ropeH",1],
            [0,4, "ropeH",1],
            undefined,
            [0,6, "ropeH",1],
            [0,7, "ropeV",1],
            [0,8, "ropeV",1],
            [0,9, "ropeV",1],
            [0,10, "ropeH",1],
            undefined,
            [0,12, "ropeH",1],
            [0,13, "ropeH",1],
            [0,14, "ropeV",1],
            [0,15, "ropeV",1],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,20, "ropeH",1],
            [0,21, "ropeV",1],
            [0,22, "ropeV",1],
            [0,23, "ropeV",1]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [0,4, "ropeH",1],
            undefined,
            [0,6, "ropeH",1],
            [0,7, "ropeV",1],
            [0,8, "ropeV",1],
            [0,9, "ropeV",1],
            [0,10, "ropeH",1],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,15, "ropeV",1],
            [0,16, "ropeV",1],
            [0,17, "ropeH",1],
            [0,18, "ropeH",1],
            [0,19, "ropeH",1],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    2: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy2',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [0,3, "ropeH",3],
            undefined,
            undefined,
            [0,6, "ropeH",3],
            undefined,
            undefined,
            [0,9, "ropeV",3],
            [0,10, "ropeH",3],
            undefined,
            undefined,
            [0,13, "ropeH",3],
            [0,14, "ropeV",3],
            [0,15, "ropeV",3],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [0,22, "ropeV",3],
            [0,23, "ropeV",3]
        ],[
            [0,0, "ropeV",3],
            [0,1, "ropeV",3],
            [0,2, "ropeV",3],
            [0,3, "ropeH",3],
            [0,4, "ropeH",3],
            undefined,
            [0,6, "ropeH",3],
            [0,7, "ropeV",3],
            [0,8, "ropeV",3],
            [0,9, "ropeV",3],
            [0,10, "ropeH",3],
            undefined,
            [0,12, "ropeH",3],
            [0,13, "ropeH",3],
            [0,14, "ropeV",3],
            [0,15, "ropeV",3],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,20, "ropeH",3],
            [0,21, "ropeV",3],
            [0,22, "ropeV",3],
            [0,23, "ropeV",3]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [0,4, "ropeH",3],
            undefined,
            [0,6, "ropeH",3],
            [0,7, "ropeV",3],
            [0,8, "ropeV",3],
            [0,9, "ropeV",3],
            [0,10, "ropeH",3],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,15, "ropeV",3],
            [0,16, "ropeV",3],
            [0,17, "ropeH",3],
            [0,18, "ropeH",3],
            [0,19, "ropeH",3],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    3: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy3',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [0,3, "ropeH",0],
            undefined,
            undefined,
            [0,6, "ropeH",0],
            undefined,
            undefined,
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            [0,0, "ropeV",0],
            [0,1, "ropeV",0],
            [0,2, "ropeV",0],
            [0,3, "ropeH",0],
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            [0,12, "ropeH",0],
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,20, "ropeH",0],
            [0,21, "ropeV",0],
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,15, "ropeV",0],
            [0,16, "ropeV",0],
            [0,17, "ropeH",0],
            [0,18, "ropeH",0],
            [0,19, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    4: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy4',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [0,3, "ropeH",0],
            undefined,
            undefined,
            [0,6, "ropeH",0],
            undefined,
            undefined,
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            [0,0, "ropeV",0],
            [0,1, "ropeV",0],
            [0,2, "ropeV",0],
            [0,3, "ropeH",0],
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            [0,12, "ropeH",0],
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,20, "ropeH",0],
            [0,21, "ropeV",0],
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,15, "ropeV",0],
            [0,16, "ropeV",0],
            [0,17, "ropeH",0],
            [0,18, "ropeH",0],
            [0,19, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    5: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy5',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [0,3, "ropeH",0],
            undefined,
            undefined,
            [0,6, "ropeH",0],
            undefined,
            undefined,
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            [0,0, "ropeV",0],
            [0,1, "ropeV",0],
            [0,2, "ropeV",0],
            [0,3, "ropeH",0],
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            [0,12, "ropeH",0],
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,20, "ropeH",0],
            [0,21, "ropeV",0],
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,15, "ropeV",0],
            [0,16, "ropeV",0],
            [0,17, "ropeH",0],
            [0,18, "ropeH",0],
            [0,19, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    7: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy7',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [0,3, "ropeH",0],
            undefined,
            undefined,
            [0,6, "ropeH",0],
            undefined,
            undefined,
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            [0,0, "ropeV",0],
            [0,1, "ropeV",0],
            [0,2, "ropeV",0],
            [0,3, "ropeH",0],
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            [0,12, "ropeH",0],
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,20, "ropeH",0],
            [0,21, "ropeV",0],
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,15, "ropeV",0],
            [0,16, "ropeV",0],
            [0,17, "ropeH",0],
            [0,18, "ropeH",0],
            [0,19, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    },
    9: {
        hp: 100,
        hpMax: 100,
        buf: 0,
        ap: 20,
        dp: 30,
        img: 'enemy9',
        gridRopeNow: -1,
        gridRopes: [[
            undefined,
            undefined,
            undefined,
            [0,3, "ropeH",0],
            undefined,
            undefined,
            [0,6, "ropeH",0],
            undefined,
            undefined,
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            [0,0, "ropeV",0],
            [0,1, "ropeV",0],
            [0,2, "ropeV",0],
            [0,3, "ropeH",0],
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            [0,12, "ropeH",0],
            [0,13, "ropeH",0],
            [0,14, "ropeV",0],
            [0,15, "ropeV",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,20, "ropeH",0],
            [0,21, "ropeV",0],
            [0,22, "ropeV",0],
            [0,23, "ropeV",0]
        ],[
            undefined,
            undefined,
            undefined,
            undefined,
            [0,4, "ropeH",0],
            undefined,
            [0,6, "ropeH",0],
            [0,7, "ropeV",0],
            [0,8, "ropeV",0],
            [0,9, "ropeV",0],
            [0,10, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined,
            [0,15, "ropeV",0],
            [0,16, "ropeV",0],
            [0,17, "ropeH",0],
            [0,18, "ropeH",0],
            [0,19, "ropeH",0],
            undefined,
            undefined,
            undefined,
            undefined
        ]]
    }
}